apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: url-shortner-ingress

spec:
  rules:
  - host: golang.local
    http:
      paths:
        - path: / 
          pathType: Prefix
          backend:
            service:
              name: golang-api-service
              port: 
                number: 8080