apiVersion: v1
kind: Service
metadata:
  name: url-shortner-service

spec:
  selector:
    app: url-shortner-api
  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  
  type: ClusterIP